# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDateTime
from PyQt5.QtGui import QIcon


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(464, 579)

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(50, 25, 131, 30))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 130, 131, 30))
        self.pushButton_2.setObjectName("pushButton_2")

        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(20, 290, 421, 281))
        self.textEdit.setObjectName("textEdit")

        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(200, 130, 251, 30))
        self.lineEdit.setPlaceholderText("请输入生成的log文件名")
        self.lineEdit.setObjectName("lineEdit")

        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 0, 51, 30))
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 190, 131, 30))
        self.pushButton_4.setObjectName("pushButton_4")

        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 190, 190, 30))
        self.lineEdit_2.setPlaceholderText("请输入包体路径")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 250, 131, 30))
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(390, 190, 60, 30))
        self.pushButton_6.setObjectName("pushButton_6")

        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 75, 131, 30))
        self.pushButton_7.setObjectName("pushButton_7")

        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 250, 251, 30))
        self.lineEdit_3.setPlaceholderText("请输入包体名称")
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.datetime = QtWidgets.QDateTimeEdit(Form)
        self.datetime.setGeometry(QtCore.QRect(200, 75, 140, 30))
        self.datetime.setCalendarPopup(True)
        self.datetime.setDateTime(QDateTime.currentDateTime())
        self.datetime.setDisplayFormat("yyyy-MM-dd HH:mm:ss")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.button1)
        self.pushButton_2.clicked.connect(Form.button2)
        self.pushButton_3.clicked.connect(Form.button3)
        self.pushButton_4.clicked.connect(Form.install)
        self.pushButton_5.clicked.connect(Form.uninstall)
        self.pushButton_6.clicked.connect(Form.get_apk)
        self.pushButton_7.clicked.connect(Form.get_timelog)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "代理测试工具"))
        Form.setWindowIcon(QIcon('Logo.jpg'))
        self.pushButton.setText(_translate("Form", "连接手机"))
        self.pushButton_2.setText(_translate("Form", "输出全局日志"))
        self.pushButton_3.setText(_translate("Form", "帮助"))
        self.pushButton_4.setText(_translate("Form", "安装APP"))
        self.pushButton_5.setText(_translate("Form", "卸载APP"))
        self.pushButton_6.setText(_translate("Form", "导入apk"))
        self.pushButton_7.setText(_translate("Form", "输出局部日志"))
